[package]
name = "day-6"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name = "matt"
path = "src/matt.rs"

[[bin]]
name = "vickz84259"
path = "src/vickz84259.rs"
